### ISSUE TITLE
Multiple hosts (:vhost) not working

### ISSUE THREAD

**Issue by Idealien** [onema/vagrant-lamp-development#9]
I suspect this is more of an issue with my local machine / environment as I have been trying multiple vagrant setups but all fail at this stage.

http://localhost will display
http://localhost/phpmyadmin will display

Any other alias or additional site added to :vosts in vagrantfile will not.

They do create entries in /etc/apache2/sites-available/ and sites-enabled/

But no access methods I have tried are successful.

I've put my vagrantfile to https://gist.github.com/Idealien/481919994bff72eedc94
The only changes made from repo source are:
- Change to precise32 from precise64
- Changed sync_folder path and off nfs (Windows)

Thanks

**Comment by onema** [comment]
It sounds like you have follow already the steps in the [tutorial](https://github.com/onema/vagrant-lamp-development/blob/master/doc/tutorial.md) and used this [file](https://github.com/onema/vagrant-lamp-development/blob/master/doc/Vagrantfile-windows.md) as a reference.

Some thoughts:
1) Try changing the name of the VM box `config.vm.box` to something like `precise64-dev` (this name is arbitrary but should be different from what you have already used), and then download the following vm:

```
config.vm.box_url = "http://files.vagrantup.com/precise64.box"
```

2) Have you run the `provision` command? After you run `vagrant up` try running `vagrant provision` or you can pass provision as a flag to the up command `vagrant up --provision`

3) In your examples you are not using the port 8080, when you try to access the VM you should do it through port 8080 as you have it in your config `config.vm.network "forwarded_port", guest: 80, host: 8080`

4) step 3 will not work if there are no records in the sites-available and sites-enabled, but when these do exist, add the host names to the list of hosts in  `/etc/hosts` for mac or `%SystemRoot%\system32\drivers\etc\hosts` in windows (see [hosts file](http://en.wikipedia.org/wiki/Hosts_%28file%29) for more info)

```
127.0.0.1         someexample.me
```

Good luck

**Comment by Idealien** [comment]
I arrived at similar state as what that tutorial showed but had not seen it previously no.

I had been putting 192.168.50.4 in the hosts file instead of 127.0.0.1. Along with the missing port # mapping that seemed to be my problems. I'd prefer not to have port # required - but having it work is better than a pretty URL that doesn't.

Thanks for help and nice vagrant setup!

**Comment by Idealien** [comment]
For anyone else encountering this issue re: port numbers and binding to port 80 (aka no port shown in domain)
In vagrantfile use:
 config.vm.network "forwarded_port", guest: 80, host: 80

Also - Ensure Skype or other software is not already binding to port 80 that would have conflict preventing the VM from doing so.
